-- Create an audit table in a WRITABLE database (replace DB/SCHEMA/TABLE)
CREATE TABLE IF NOT EXISTS YOUR_WRITABLE_DB.PUBLIC.CHAT_DATA_AUDIT (
  TS TIMESTAMP_NTZ,
  PROMPT STRING,
  SQL_TEXT STRING,
  ROWCOUNT INTEGER
);
